frase = str(input('Digite uma frase qualquer:')).strip().upper()
print('-'*30)
letra = str(input('Qual letra deseja procurar na frase?:'))
print('='*60)
print(f'Quantidade de letras A na sua frase: {frase.count(letra)}')
print('='*60)
print(f'Em que posição A apareceu pela primeira vez?: {frase.find(letra)} para o programa, e {frase.find(letra)+1} para nós.')
print('='*60)
print(f'Em que posição ela apareceu pela última vez?: {frase.rfind(letra)} para o programa, e {frase.rfind(letra)+1} para nós.')
