numero = str(input('Digite um numero entre 1 e 9999:'))
print('='*40)
print(f'Unidades: {len(numero.strip())}')
print('='*20)
print(f'Dezenas:  {numero[2]}')
print('='*20)
print(f'Centenas: {numero[1]}')
print('='*20)
print(f'Milhar:   {numero[0]}')
